// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.UI.Input.Post
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\UI\Input\Post\PostTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PostTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<script setup>\r\nimport { ref, defineProps, defineEmits } from \'vue\';\r\n\r\nconst e" +
                    "mit = defineEmits([\"create\"]);\r\n\r\nconst titleValue = ref(\'\');         // Binding" +
                    " for the title input\r\nconst descriptionValue = ref(\'\');  // Binding for the desc" +
                    "ription textarea\r\n\r\nfunction emitCreate() {\r\n  emit(\"create\", {\r\n    title: titl" +
                    "eValue.value,\r\n    description: descriptionValue.value\r\n  });\r\n\r\n  titleValue.va" +
                    "lue = \'\';\r\n  descriptionValue.value = \'\';\r\n}\r\n\r\nconst props = defineProps({\r\n  s" +
                    "howTitle: {\r\n    type: Boolean,\r\n    default: false,\r\n  },\r\n  titlePlaceholder: " +
                    "{\r\n    type: String,\r\n    default: \'Title\',\r\n  },\r\n  descriptionPlaceholder: {\r\n" +
                    "    type: String,\r\n    default: \'Write a description...\',\r\n  },\r\n  createButtonT" +
                    "ext: {\r\n    type: String,\r\n    default: \'Create\',\r\n  },\r\n  colSpan: {\r\n    type:" +
                    " [Number, String],\r\n    default: 3,\r\n  },\r\n  rows: {\r\n    type: [Number, String]" +
                    ",\r\n    default: 4,\r\n  },\r\n});\r\n\r\nfunction autoGrow(event) {\r\n  event.target.styl" +
                    "e.height = \'auto\';\r\n  event.target.style.height = (event.target.scrollHeight) + " +
                    "\'px\';\r\n}\r\n</script>\r\n\r\n<template>\r\n  <!-- Wrap in a flex container -->\r\n  <div\r\n" +
                    "       class=\"flex flex-col rounded-lg border border-gray-300 shadow-sm focus-wi" +
                    "thin:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500\">\r\n    <" +
                    "!-- Main content -->\r\n    <div class=\"flex-grow overflow-hidden\">\r\n      <div v-" +
                    "if=\"showTitle\">\r\n        <label for=\"title\"\r\n               class=\"sr-only\">Titl" +
                    "e</label>\r\n        <input v-model=\"titleValue\"\r\n               type=\"text\"\r\n    " +
                    "           name=\"title\"\r\n               id=\"title\"\r\n               class=\"block " +
                    "w-full border-0 pt-2.5 text-lg font-medium\r\n        placeholder:text-gray-400 fo" +
                    "cus:ring-0\"\r\n               :placeholder=\"titlePlaceholder\" />\r\n      </div>\r\n  " +
                    "    <label for=\"description\"\r\n             class=\"sr-only\">Description</label>\r\n" +
                    "      <textarea v-model=\"descriptionValue\"\r\n                :class=\"{ \'pt-2.5\': " +
                    "!showTitle }\"\r\n                rows=\"2\"\r\n                name=\"description\"\r\n   " +
                    "             id=\"description\"\r\n                v-on:input=\"autoGrow($event)\"\r\n  " +
                    "              class=\"block w-full resize-none border-0 py-0 text-gray-900 placeh" +
                    "older:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6\"\r\n                :plac" +
                    "eholder=\"descriptionPlaceholder\"></textarea>\r\n      <!-- Spacer element to match" +
                    " the height of the toolbar -->\r\n      <div aria-hidden=\"true\"\r\n           v-if=\"" +
                    "$slots.attributes\">\r\n        <div class=\"py-2\">\r\n          <div class=\"h-9\"></di" +
                    "v>\r\n        </div>\r\n        <div class=\"h-px\"></div>\r\n        <div class=\"py-2\">" +
                    "\r\n          <div class=\"py-px\">\r\n            <div class=\"h-9\"></div>\r\n          " +
                    "</div>\r\n        </div>\r\n        <!-- Slot for additional attributes like assigne" +
                    "e, due date, tags, etc. -->\r\n        <div class=\"flex flex-nowrap justify-end sp" +
                    "ace-x-2 px-2 py-2 sm:px-3\">\r\n          <slot name=\"attributes\"></slot>\r\n        " +
                    "</div>\r\n      </div>\r\n    </div>\r\n    <!-- Footer (Actions) -->\r\n    <div\r\n     " +
                    "    :class=\"[$slots.actions ? \'justify-between\' : \'justify-end\', \'border-t borde" +
                    "r-gray-200 px-2 py-2 sm:px-3 flex items-center space-x-3\']\">\r\n      <!-- Slot fo" +
                    "r actionable controls like attaching a file or other actions -->\r\n      <slot na" +
                    "me=\"actions\"></slot>\r\n      <div class=\"flex-shrink-0\">\r\n        <button @click=" +
                    "\"emitCreate\"\r\n                type=\"button\"\r\n                class=\"inline-flex " +
                    "items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white" +
                    " shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 foc" +
                    "us-visible:outline-offset-2 focus-visible:outline-indigo-600\">{{\r\n              " +
                    "    createButtonText }}</button>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</template" +
                    ">\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
