//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:7.0.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aryzac.IO.Modules.Nuxt.Templates.Components.UI.Input.Checkbox {
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    
    public partial class CheckboxTemplate : IntentTemplateBase<object> {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 8 ""
            this.Write(@"
<script setup>
const props = defineProps({
  modelValue: Boolean,
  label: String,
  description: String,
  name: String,
  id: String,
});

const emit = defineEmits([""update:modelValue""]);
</script>

<template>
  <div class=""relative flex gap-x-3"">
    <div class=""flex h-6 items-center"">
      <input
        :id=""id""
        :name=""name""
        type=""checkbox""
        v-bind:value=""modelValue""
        v-on:input=""updateValue($event)""
        class=""h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600""
      />
    </div>
    <div class=""text-sm leading-6"">
      <label :for=""id"" class=""font-medium text-gray-900"">{{ label }}</label>
      <p class=""text-gray-500"">{{ description }}</p>
    </div>
  </div>
</template>
");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
