// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.GetMany.ListComponent
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ListComponentTemplate : IntentTemplateBase<Intent.Modelers.Types.ServiceProxies.Api.OperationModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"

    var endpoint = GetEndpoint();

            
            #line default
            #line hidden
            this.Write("<script setup lang=\"ts\">\r\nimport { ");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResponseClassName()));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/models/");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceName()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDTOModelName()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n\r\nconst props = withDefaults(defineProps<{\r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromRoute)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 21 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 21 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 22 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromHeader)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromQuery)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 38 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    items: ");
            
            #line 41 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResponseClassName()));
            
            #line default
            #line hidden
            this.Write("[],\r\n    navigateToPath: string\r\n}>(), {\r\n    navigateToPath: \'/\'\r\n});\r\n\r\nconst ");
            
            #line 47 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableServiceName().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy = use");
            
            #line 47 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableServiceName().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(@"Proxy();

// Navigate to the given URL
const navigate = async (e) => {
    await navigateTo(`${props.navigateToPath}/${e.item.id}`);
}
</script>

<template>

    <ui-view-list :items=""items""
                  @item-clicked=""navigate"">
        <template #default=""{ item, index }"">
            <");
            
            #line 60 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServicePath()));
            
            #line default
            #line hidden
            this.Write("-");
            
            #line 60 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListComponent\ListComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write("-list-item :item=\"item\" />\r\n        </template>\r\n    </ui-view-list>\r\n\r\n</templat" +
                    "e>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
