// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.UI.Columns.Index
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\UI\Columns\Index\IndexTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class IndexTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<script setup lang=\"ts\">\r\nconst debug = useDebug();\r\n\r\nconst props = defineProp" +
                    "s({\r\n    asideWidth: {\r\n        type: String,\r\n        default: \'w-96\'\r\n    },\r\n" +
                    "    navWidth: {\r\n        type: String,\r\n        default: \'w-96\'\r\n    }\r\n});\r\n</s" +
                    "cript>\r\n\r\n<template>\r\n    <div class=\"h-full relative z-0 flex flex-1 overflow-h" +
                    "idden\">\r\n\r\n        <!-- Nav slot -->\r\n        <nav v-if=\"$slots.nav\"\r\n          " +
                    "   :class=\"[navWidth, \'relative\', \'hidden\', \'flex-shrink-0\', \'overflow-y-auto\', " +
                    "\'border-r\', \'border-gray-200\', \'xl:flex\', \'xl:flex-col\', \'order-0\']\">\r\n         " +
                    "   <div class=\"h-full inset-0 py-6 px-4 sm:px-6 lg:px-8\">\r\n                <div " +
                    "class=\"h-full rounded-lg\"\r\n                     :class=\"{ \'border-2 border-dashe" +
                    "d border-gray-200\': debug }\">\r\n                    <slot name=\"nav\" />\r\n        " +
                    "        </div>\r\n            </div>\r\n        </nav>\r\n\r\n        <!-- Main slot -->" +
                    "\r\n        <main\r\n              class=\"relative z-0 flex-1 overflow-y-auto focus:" +
                    "outline-none xl:order-1\">\r\n            <div class=\"h-full inset-0 py-6 px-4 sm:p" +
                    "x-6 lg:px-8\">\r\n                <div class=\"h-full rounded-lg\"\r\n                 " +
                    "    :class=\"{ \'border-2 border-dashed border-gray-200\': debug }\">\r\n             " +
                    "       <slot />\r\n                </div>\r\n            </div>\r\n        </main>\r\n\r\n" +
                    "        <!-- Aside slot -->\r\n        <aside v-if=\"$slots.aside\"\r\n               " +
                    ":class=\"[asideWidth, \'relative\', \'hidden\', \'flex-shrink-0\', \'overflow-y-auto\',\r\n" +
                    "                   \'border-l\', \'border-gray-200\', \'xl:flex\', \'xl:flex-col\', \'ord" +
                    "er-2\']\">\r\n            <div class=\"h-full inset-0 py-6 px-4 sm:px-6 lg:px-8\">\r\n  " +
                    "              <div class=\"h-full rounded-lg\"\r\n                     :class=\"{ \'bo" +
                    "rder-2 border-dashed border-gray-200\': debug }\">\r\n                    <slot name" +
                    "=\"aside\" />\r\n                </div>\r\n            </div>\r\n        </aside>\r\n    <" +
                    "/div>\r\n</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
