// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.Layout.AppBar.Index
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\Layout\AppBar\Index\IndexTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class IndexTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<script setup lang=\"ts\">\r\nimport {\r\n    Menu,\r\n    MenuButton,\r\n    MenuItem,\r\n" +
                    "    MenuItems,\r\n} from \"@headlessui/vue\";\r\n\r\nconst userNavigation = [\r\n    { nam" +
                    "e: \"Your profile\", href: \"#\" },\r\n    { name: \"Sign out\", href: \"#\" },\r\n];\r\n\r\ncon" +
                    "st { openSidebar } = useSidebar();\r\n</script>\r\n\r\n<template>\r\n    <div\r\n         " +
                    "class=\"sticky top-0 z-40 flex items-center h-16 px-4 bg-white border-b border-gr" +
                    "ay-200 shadow-sm shrink-0 gap-x-4 sm:gap-x-6 sm:px-6 lg:px-8\">\r\n        <button " +
                    "type=\"button\"\r\n                class=\"-m-2.5 p-2.5 text-gray-700 lg:hidden\"\r\n   " +
                    "             @click=\"openSidebar\">\r\n            <span class=\"sr-only\">Open sideb" +
                    "ar</span>\r\n            <Icon name=\"heroicons:bars-3\"\r\n                  class=\"w" +
                    "-6 h-6\"\r\n                  aria-hidden=\"true\" />\r\n        </button>\r\n\r\n        <" +
                    "!-- Separator -->\r\n        <div class=\"w-px h-6 bg-gray-200 lg:hidden\"\r\n        " +
                    "     aria-hidden=\"true\" />\r\n\r\n        <div class=\"flex self-stretch flex-1 gap-x" +
                    "-4 lg:gap-x-6\">\r\n            <form class=\"relative flex flex-1\"\r\n               " +
                    "   action=\"#\"\r\n                  method=\"GET\">\r\n                <label for=\"sear" +
                    "ch-field\"\r\n                       class=\"sr-only\">Search</label>\r\n              " +
                    "  <Icon name=\"heroicons:magnifying-glass-20-solid\"\r\n                      class=" +
                    "\"absolute inset-y-0 left-0 w-5 h-full text-gray-400 pointer-events-none\"\r\n      " +
                    "                aria-hidden=\"true\" />\r\n                <input id=\"search-field\"\r" +
                    "\n                       class=\"block w-full h-full py-0 pl-8 pr-0 text-gray-900 " +
                    "border-0 placeholder:text-gray-400 focus:ring-0 sm:text-sm\"\r\n                   " +
                    "    placeholder=\"Search...\"\r\n                       type=\"search\"\r\n             " +
                    "          name=\"search\" />\r\n            </form>\r\n            <div class=\"flex it" +
                    "ems-center gap-x-4 lg:gap-x-6\">\r\n                <button type=\"button\"\r\n        " +
                    "                class=\"-m-2.5 p-2.5 text-gray-400 hover:text-gray-500\">\r\n       " +
                    "             <span class=\"sr-only\">View notifications</span>\r\n                  " +
                    "  <Icon name=\"heroicons:bell\"\r\n                          class=\"w-6 h-6\"\r\n      " +
                    "                    aria-hidden=\"true\" />\r\n                </button>\r\n\r\n        " +
                    "        <!-- Separator -->\r\n                <div class=\"hidden lg:block lg:h-6 l" +
                    "g:w-px lg:bg-gray-200\"\r\n                     aria-hidden=\"true\" />\r\n\r\n          " +
                    "      <!-- Profile dropdown -->\r\n                <Menu as=\"div\"\r\n               " +
                    "       class=\"relative\">\r\n                    <MenuButton class=\"-m-1.5 flex ite" +
                    "ms-center p-1.5\">\r\n                        <span class=\"sr-only\">Open user menu<" +
                    "/span>\r\n                        <img class=\"w-8 h-8 rounded-full bg-gray-50\"\r\n  " +
                    "                           src=\"https://images.unsplash.com/photo-1472099645785-" +
                    "5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&f" +
                    "acepad=2&w=256&h=256&q=80\"\r\n                             alt=\"\" />\r\n            " +
                    "            <span class=\"hidden lg:flex lg:items-center\">\r\n                     " +
                    "       <span class=\"ml-4 text-sm font-semibold leading-6 text-gray-900\"\r\n       " +
                    "                           aria-hidden=\"true\">Tom Cook</span>\r\n                 " +
                    "           <Icon name=\"heroicons:chevron-down-20-solid\"\r\n                       " +
                    "           class=\"w-5 h-5 ml-2 text-gray-400\"\r\n                                 " +
                    " aria-hidden=\"true\" />\r\n                        </span>\r\n                    </M" +
                    "enuButton>\r\n                    <transition enter-active-class=\"transition durat" +
                    "ion-100 ease-out\"\r\n                                enter-from-class=\"transform s" +
                    "cale-95 opacity-0\"\r\n                                enter-to-class=\"transform sc" +
                    "ale-100 opacity-100\"\r\n                                leave-active-class=\"transi" +
                    "tion duration-75 ease-in\"\r\n                                leave-from-class=\"tra" +
                    "nsform scale-100 opacity-100\"\r\n                                leave-to-class=\"t" +
                    "ransform scale-95 opacity-0\">\r\n                        <MenuItems\r\n             " +
                    "                      class=\"absolute right-0 z-10 mt-2.5 w-32 origin-top-right " +
                    "rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none\">\r\n" +
                    "                            <MenuItem v-for=\"item in userNavigation\"\r\n          " +
                    "                            :key=\"item.name\"\r\n                                  " +
                    "    v-slot=\"{ active }\">\r\n                            <a :href=\"item.href\"\r\n    " +
                    "                           :class=\"[\r\n                                       act" +
                    "ive ? \'bg-gray-50\' : \'\',\r\n                                       \'block px-3 py-" +
                    "1 text-sm leading-6 text-gray-900\',\r\n                                   ]\">{{ it" +
                    "em.name }}</a>\r\n                            </MenuItem>\r\n                       " +
                    " </MenuItems>\r\n                    </transition>\r\n                </Menu>\r\n     " +
                    "       </div>\r\n        </div>\r\n    </div>\r\n</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
