// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.UI.Input.RadioButton
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\UI\Input\RadioButton\RadioButtonTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RadioButtonTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<script setup>
const props = defineProps({
  modelValue: [String, Number],
  label: String,
  name: String,
  id: String,
});

const emit = defineEmits([""update:modelValue""]);
</script>

<template>
  <div class=""flex items-center gap-x-3"">
    <input
      :id=""id""
      :name=""name""
      type=""radio""
      v-bind:value=""modelValue""
      v-on:input=""updateValue($event)""
      class=""h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-600""
    />
    <label
      :for=""id""
      class=""block text-sm font-medium leading-6 text-gray-900""
      >{{ label }}</label
    >
  </div>
</template>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
