// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.GetMany.ListItemComponent
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ListItemComponentTemplate : IntentTemplateBase<Intent.Modelers.Types.ServiceProxies.Api.OperationModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"

    var endpoint = GetEndpoint();

            
            #line default
            #line hidden
            this.Write("<script setup lang=\"ts\">\r\nimport { ");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResponseClassName()));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/models/");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceName()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDTOModelName()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n\r\nconst props = withDefaults(defineProps<{\r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromRoute)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 21 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 21 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 22 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromHeader)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromQuery)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 38 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    item: ");
            
            #line 41 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\GetMany\ListItemComponent\ListItemComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResponseClassName()));
            
            #line default
            #line hidden
            this.Write(@",
}>(), {
});
</script>

<template>

    <div class=""min-w-0 flex-auto"">
        <div class=""flex items-start gap-x-3"">
            <p class=""text-sm font-semibold leading-6 text-gray-900"">{{
                item.name }}</p>
        </div>
        <div
            class=""mt-1 flex items-center gap-x-2 text-xs leading-5 text-gray-500"">
            <p class=""whitespace-nowrap"">{{ item.description }}</p>
        </div>
    </div>
    <div class=""flex flex-none items-center gap-x-4"">
        <!-- Chevron Right Icon -->
        <icon name=""heroicons:chevron-right-20-solid""
                class=""h-5 w-5 flex-none text-gray-400""
                aria-hidden=""true"" />
    </div>

</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
