// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.Layout.SideBar.Navigation
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\Layout\SideBar\Navigation\NavigationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class NavigationTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<script setup lang=""ts"">
import { Item } from '~/structs/navigation';
import { useRoute, useRouter, RouteLocationRaw } from 'vue-router';

interface Props {
    items: Item[];
}

defineProps<Props>();

const route = useRoute();
const router = useRouter();
const isActive = (to: RouteLocationRaw) => route.fullPath === router.resolve(to).fullPath;
</script>

<template>
    <li v-for=""item in items""
        :key=""item.name"">
        <nuxt-link :to=""item.to""
                   @click.prevent=""router.push(item.to)""
                   :class=""[
                           isActive(item.to)
                               ? 'bg-gray-50 text-indigo-600'
                               : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50',
                           'group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold',
                       ]"">
            <Icon :name=""item.icon""
                  :class=""[
                          isActive(item.to)
                              ? 'text-indigo-600'
                              : 'text-gray-400 group-hover:text-indigo-600',
                          'h-6 w-6 shrink-0',
                      ]""
                  aria-hidden=""true"" />
            {{ item.name }}
        </nuxt-link>
    </li>
</template>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
