// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.Layout.SideBar.Section
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\Layout\SideBar\Section\SectionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class SectionTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<script setup lang=""ts"">
import { Section } from ""~/structs/navigation"";

interface Props {
  sections: Section[];
}

defineProps<Props>();

const components = {
  ""navigation"": resolveComponent(""layout-sidebar-navigation""),
};

const getComponent = (section: Section) => {
  return components[section.component];
};
</script>

<template>
  <li v-for=""section in sections""
      :key=""section.id""
      :data-section-id=""section.id"">
    <div v-if=""section.title""
         class=""text-xs font-semibold leading-6 text-gray-400"">
      {{ section.title }}
    </div>
    <ul role=""list""
        class=""mt-2 -mx-2 space-y-1"">
      <component :is=""getComponent(section)""
                 v-bind=""section"" />
    </ul>
  </li>
</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
