//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:7.0.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aryzac.IO.Modules.Nuxt.Templates.Components.UI.Container.ConstrainedPadded {
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    
    public partial class ConstrainedPaddedTemplate : IntentTemplateBase<object> {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 8 ""
            this.Write("\r\n<template>\r\n  <div class=\"mx-auto max-w-7xl px-4 sm:px-6 lg:px-8\">\r\n    <slot /" +
                    ">\r\n  </div>\r\n</template>\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
