// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Nuxt.Templates.Components.PostComponent
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PostComponentTemplate : IntentTemplateBase<Intent.Modelers.Types.ServiceProxies.Api.OperationModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"

    var endpoint = GetEndpoint();

            
            #line default
            #line hidden
            this.Write("<script setup lang=\"ts\">\r\n");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    if (endpoint.Inputs.FirstOrDefault(x => x.Source == HttpInputSource.FromBody) != null) 
    { 
        var bodyParam = endpoint.Inputs.First(x => x.Source == HttpInputSource.FromBody);

            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBodyClassName()));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/models/");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceName()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDTOModelName()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 20 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("\r\nconst props = withDefaults(defineProps<{\r\n");
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromRoute)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromHeader)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 38 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 41 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    foreach (var input in endpoint.Inputs.Where(x => x.Source == HttpInputSource.FromQuery)) 
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputName(input)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(GetInputType(input))));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            
            #line 49 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    if (endpoint.Inputs.FirstOrDefault(x => x.Source == HttpInputSource.FromBody) != null) 
    { 

            
            #line default
            #line hidden
            this.Write("    command: ");
            
            #line 53 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBodyClassName()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 54 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    sectionTitle: string,\r\n    sectionDescription: string,\r\n}>(), {\r\n    sectionT" +
                    "itle: \'");
            
            #line 60 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceProxyMethodNameForTitle()));
            
            #line default
            #line hidden
            this.Write("\',\r\n    sectionDescription: \'");
            
            #line 61 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceProxyMethodCommentForDescription()));
            
            #line default
            #line hidden
            this.Write("\',\r\n});\r\n\r\nconst ");
            
            #line 64 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableServiceName().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy = use");
            
            #line 64 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableServiceName().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Proxy();\r\n\r\nconst ");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBodyClassName().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = async (");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputsWithTypes()));
            
            #line default
            #line hidden
            this.Write(") => {\r\n    await ");
            
            #line 67 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableServiceName().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 67 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceProxyMethodName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 67 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputs()));
            
            #line default
            #line hidden
            this.Write(");\r\n}\r\n</script>\r\n\r\n<template>\r\n\r\n    <ui-editor-section :title=\"sectionTitle\"\r\n " +
                    "                      :description=\"sectionDescription\">\r\n\r\n");
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    foreach (var dtoField in GetDTOModelFields()) 
    { 

            
            #line default
            #line hidden
            this.Write("        <ui-input-textbox v-model=\"command.");
            
            #line 80 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtoField.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"\r\n                          label=\"");
            
            #line 81 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtoField.Comment ?? dtoField.Name.ToSentenceCase()));
            
            #line default
            #line hidden
            this.Write("\" />\r\n\r\n");
            
            #line 83 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("        <template #actions>\r\n            <button type=\"button\"\r\n                 " +
                    "   class=\"text-sm font-semibold leading-6 text-gray-900\">Cancel</button>\r\n      " +
                    "      <button type=\"button\"\r\n                    @click=\"");
            
            #line 90 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBodyClassName().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 90 "D:\src\aryzac-io\aryzac.io.Modules.Nuxt\Aryzac.IO.Modules.Nuxt\Templates\Components\PostComponent\PostComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInputs()));
            
            #line default
            #line hidden
            this.Write(@")""
                    class=""rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"">Save</button>
        </template>

    </ui-editor-section>

</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
